- hosts: localhost
  tasks:
   - name: installing web server
     package:
       name: "httpd"
       state: present

   - name: copy the file in webserver
     copy:
       src: /var/lib/jenkins/workspace/ansible/
       dest: /var/www/html/

   - name: startig the web server
     service:
             name: "httpd"
             state: started
             enabled: yes


